py visualize_agent_status_group_multiprocess_1.py outcomes/Debugging/Test_A
py visualize_agent_status_group_multiprocess_2.py outcomes/Debugging/Test_A
py visualize_agent_status_group_multiprocess_3.py outcomes/Debugging/Test_A
py visualize_agent_status_group_multiprocess_1.py outcomes/Debugging/Test_B
py visualize_agent_status_group_multiprocess_2.py outcomes/Debugging/Test_B
py visualize_agent_status_group_multiprocess_3.py outcomes/Debugging/Test_B